TITLE LAB3 (.EXE MODEL)
;
; EARL TIMOTHY MALAKI
; CMSC 131 LAB 3
;
;--------------------------------------
STACKSEG SEGMENT PARA 'Stack'
STACKSEG ENDS
;--------------------------------------
DATASEG SEGMENT PARA 'Data'
	CHAR_INPUT DB ?, 0AH, 0DH, "$"

	STR_UPCASELET DB "Uppercase Letter$"
	STR_LOWCASELET DB "Lowercase Letter$"
	STR_DIGIT DB "Digit$"
	STR_SPECIAL DB "Special Character$"

	HEX_BIG_A DB 41H
	HEX_BIG_Z DB 5AH

	HEX_SMALL_A DB 61H
	HEX_SMALL_Z DB 7AH

	HEX_NUM_0 DB 30H
	HEX_NUM_9 DB 39H


DATASEG ENDS
;--------------------------------------
CODESEG SEGMENT PARA 'Code'
	ASSUME SS:STACKSEG, DS:DATASEG, CS:CODESEG
START:
	; initialize DS
	MOV AX, DATASEG
	MOV DS, AX

	; get input character
	MOV AH, 10H
	INT 16H
	MOV CHAR_INPUT, AL

	; print inputted character
	MOV AH, 09H
	LEA DX, CHAR_INPUT
	INT 21H

	; check if input Lowercase Letter
	CMP CHAR_INPUT, 'a'
	JAE ABOVE_OR_EQUAL_SMALL_A

	JMP CHECK_IF_UPPER

ABOVE_OR_EQUAL_SMALL_A:
	CMP CHAR_INPUT, 'z'
	JBE LOWERCASE

	JMP SPECIALCHAR

CHECK_IF_UPPER:
	CMP CHAR_INPUT, 'A'
	JAE ABOVE_OR_EQUAL_BIG_A

	JMP CHECK_IF_DIGIT

ABOVE_OR_EQUAL_BIG_A:
	CMP CHAR_INPUT, 'Z'
	JBE UPPERCASE

	JMP SPECIALCHAR

CHECK_IF_DIGIT:
	CMP CHAR_INPUT, '0'
	JAE ABOVE_OR_EQUAL_0

	JMP SPECIALCHAR

ABOVE_OR_EQUAL_0:
	CMP CHAR_INPUT, '9'
	JBE DIGIT

	JMP SPECIALCHAR	


UPPERCASE:
	MOV AH, 09H
	LEA DX, STR_UPCASELET
	INT 21H

	JMP EXIT

LOWERCASE:
	MOV AH, 09H
	LEA DX, STR_LOWCASELET
	INT 21H

	JMP EXIT

DIGIT:
	MOV AH, 09H
	LEA DX, STR_DIGIT
	INT 21H

	JMP EXIT

SPECIALCHAR:
	MOV AH, 09H
	LEA DX, STR_SPECIAL
	INT 21H


EXIT:
	; exit
	MOV AH, 4CH
	INT 21H
CODESEG ENDS
END START